### ISSUE TITLE
Session code error

### ISSUE THREAD

**Issue by vnl** [scarytom/payslip-retriever#3]
Hi there, this script is like a boon currently. We will be losing access to ADP soon and so they asked us to download all the data. Most of the scripts are for some newer version of ADP and what we have is one which works only on IE and using frames. I thought that tech is not supported anymore lol. 

I have one issue where the session code is not sent back or got.
Obtaining session token...
Error: sessionToken not found in response from ADP.

Cookies.txt contents: myfreedom.adp.com	FALSE	/	FALSE	0	BIGipServerp_myfreedom.adp.com_web	430904492.27392.0000

Any possibility of debugging it? I can F12 and give you the details if necessary.

**Comment by adamgibbins** [comment]
Hi, sadly this isn't likely to be maintained going forwards as @scarytom has moved on from the company that used ADP and I, the only other maintainer now have access to the ADP mobile app which allows PDF downloads of payslips which meets my need.

This breaks fairly often due to ADP making minor but irritating changes to their site. The last time it broke it was due to them changing the session download URL from `fress1` to `fress2` - but I just tried reverting that and it still fails. I'd suggest digging through the IE Network Inspector to see if you can replicate the relevant queries it's making, it's a time consuming process.

Just FYI, to my knowledge this code has only ever been used for one companies payslips - so its possible it might not even work for you when you get it working without modification.

Sorry for your predicament!

**Comment by vnl** [comment]
Not at all.. Thanks for the reply. I have the network data from IE and you are right it is bonkers. I appreciate something has been shared as open source. So no complaints. 

Edit: I checked the dev tools. It shows the exact same request url and IE gets the sessionToken. possibly I need to debug this further.
